version: 0.1
phases:
  install:
    commands:
      - serverless_all_aws/npm install time
      - aws cloudformation package --template-file serverless_all_aws/samTemplate.yaml --s3-bucket serverless.tutorial.mpapetti
                                   --output-template-file serverless_all_aws/NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - serverless_all_aws/samTemplate.yaml
